# Custom Secret Patterns for The Sovereign's Dilemma

# Game-specific API keys and tokens
game-api-keys:
  - pattern: '\b(nvapi-[a-zA-Z0-9]{32,})\b'
    name: "NVIDIA NIM API Key"
    description: "NVIDIA NIM API key detected"
    severity: "CRITICAL"

  - pattern: '\b(sk-[a-zA-Z0-9]{48,})\b'
    name: "OpenAI API Key"
    description: "OpenAI API key detected"
    severity: "CRITICAL"

  - pattern: '\b(steamkey_[a-zA-Z0-9]{32})\b'
    name: "Steam API Key"
    description: "Steam API key detected"
    severity: "HIGH"

  - pattern: '\b(itch_api_[a-zA-Z0-9]{40})\b'
    name: "Itch.io API Key"
    description: "Itch.io API key detected"
    severity: "MEDIUM"

# Database and infrastructure secrets
database-secrets:
  - pattern: 'mongodb://[^:]+:[^@]+@[^/]+'
    name: "MongoDB Connection String"
    description: "MongoDB connection string with credentials"
    severity: "HIGH"

  - pattern: 'postgresql://[^:]+:[^@]+@[^/]+'
    name: "PostgreSQL Connection String"
    description: "PostgreSQL connection string with credentials"
    severity: "HIGH"

  - pattern: 'Server=.*;User Id=.*;Password=.*;'
    name: "SQL Server Connection String"
    description: "SQL Server connection string with credentials"
    severity: "HIGH"

# Unity and game development secrets
unity-secrets:
  - pattern: '\b[A-Za-z0-9]{8}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{12}\b'
    name: "Unity Cloud Build API Key"
    description: "Unity Cloud Build API key detected"
    severity: "MEDIUM"
    context:
      - "unity"
      - "cloud"
      - "build"

  - pattern: 'UnityCloudProjectId:\s*[a-f0-9-]{36}'
    name: "Unity Cloud Project ID"
    description: "Unity Cloud Project ID detected"
    severity: "LOW"

# JWT and session tokens
authentication-tokens:
  - pattern: 'eyJ[A-Za-z0-9_/+-]*\.eyJ[A-Za-z0-9_/+-]*\.[A-Za-z0-9_/+-]*'
    name: "JWT Token"
    description: "JSON Web Token detected"
    severity: "MEDIUM"

  - pattern: '\b[A-Za-z0-9]{32,}\b'
    name: "Generic API Token"
    description: "Generic API token pattern"
    severity: "LOW"
    context:
      - "token"
      - "api"
      - "key"
      - "secret"

# Cloud service secrets
cloud-secrets:
  - pattern: 'AKIA[0-9A-Z]{16}'
    name: "AWS Access Key ID"
    description: "AWS Access Key ID detected"
    severity: "HIGH"

  - pattern: '[0-9a-zA-Z/+]{40}'
    name: "AWS Secret Access Key"
    description: "AWS Secret Access Key detected"
    severity: "CRITICAL"
    context:
      - "aws"
      - "secret"

  - pattern: '\b[A-Za-z0-9]{24}\.[A-Za-z0-9]{6}\.[A-Za-z0-9_-]{27}\b'
    name: "Discord Bot Token"
    description: "Discord Bot Token detected"
    severity: "MEDIUM"

# Development and CI secrets
development-secrets:
  - pattern: 'ghp_[A-Za-z0-9]{36}'
    name: "GitHub Personal Access Token"
    description: "GitHub Personal Access Token detected"
    severity: "HIGH"

  - pattern: 'glpat-[A-Za-z0-9_-]{20}'
    name: "GitLab Personal Access Token"
    description: "GitLab Personal Access Token detected"
    severity: "HIGH"

# Custom application secrets
application-secrets:
  - pattern: 'SOVEREIGNS_DILEMMA_[A-Z_]+=[A-Za-z0-9+/=]+'
    name: "Application Secret"
    description: "Sovereign's Dilemma application secret detected"
    severity: "HIGH"

  - pattern: 'political_sim_key_[a-f0-9]{32}'
    name: "Political Simulation Key"
    description: "Political simulation encryption key detected"
    severity: "CRITICAL"

# Encryption keys and certificates
crypto-secrets:
  - pattern: '-----BEGIN [A-Z ]+-----[\s\S]*-----END [A-Z ]+-----'
    name: "Private Key or Certificate"
    description: "Private key or certificate detected"
    severity: "CRITICAL"

  - pattern: '\b[A-Fa-f0-9]{64}\b'
    name: "SHA256 Hash or Key"
    description: "Potential SHA256 hash or encryption key"
    severity: "MEDIUM"
    context:
      - "key"
      - "hash"
      - "secret"